### ISSUE TITLE
Software Serial

### ISSUE THREAD

**Issue by tchinou1** [elcojacobs/ShiftPWM#6]
Hi,
there seems to have incompatibility between Software serial communcation and ShiftPWM. I can't receive anything from the serial software if this line (and of course all the rest needed for ShiftPWM) is there: ShiftPWM.Start(pwmFrequency,maxBrightness);. 
Any solution ? I really need both of them. 

Thanks
William

**Comment by PaulStoffregen** [comment]
Do you mean the SoftwareSerial library?

There's basically no hope of getting that to work reliably with any interrupt-based library like ShiftPWM, which spends more than a fraction of 1 bit time in its interrupt.

**Comment by tchinou1** [comment]
Yes... Do you know an alternative solution I need to pass from a Spark (arduino compatible) to an arduino uno 30 variables...

**Comment by PaulStoffregen** [comment]
Replace the Uno with a board that has an available hardware serial port.

Or kludge a way to get data into the Uno's serial RX pin.

**Comment by tchinou1** [comment]
Ok. Thanks !

**Comment by tchinou1** [comment]
Do you know if there is also a incompatibility with a press button, I can't get a button working if this line is not commented: ShiftPWM.Start(pwmFrequency,maxBrightness);  

Thanks 
William
